Added MinimumElementSnippet
iluwatar/30-seconds-of-java pull request #129
Opened 2022-10-05 07:49 UTC by varada1110

2022-10-10 16:09 UTC, iluwatar requested changes
Looks good, but the build is failing due to Checkstyle errors

2022-10-29 06:15 UTC, iluwatar requested changes
Two minor comments, then we can merge

2022-10-29 06:15 UTC, iluwatar commented on README.md
> +        }
The intendation isn't right here

2022-10-29 06:15 UTC, iluwatar commented on build.gradle
> +    testImplementation 'junit:junit:4.13.1'
The dependency should not appear twice

2022-11-20 12:56 UTC, iluwatar requested changes
Looks good otherwise, but the build is still failing. I can't merge until the Checkstyle issues have been fixed.

2022-12-01 16:21 UTC, PraveenNanda124 reviewed
Good work

2023-02-14 19:53 UTC, closed without merging