Hacktober fest raje pr1
iluwatar/30-seconds-of-java pull request #226
Opened 2024-10-13 15:00 UTC by rajeshsgr

Code Snippet for File Rename

2024-10-13 19:09 UTC, Ritabrata1080 requested changes

2024-10-13 19:09 UTC, Ritabrata1080 commented on src/main/java/file/FileRenameSnippet.java
> + * Copyright (c) 2017-2022 Ilkka Seppälä
* Copyright (c) 2017-2024 Ilkka Seppälä

2024-10-13 19:10 UTC, Ritabrata1080 commented
Changes LGTM ✅. 

Shall the copyright year be 2017-2024 or 2017-2022?
Please confirm @iluwatar

2024-10-13 19:11 UTC, Ritabrata1080 reviewed
Please squash all the commits to a single commit.

2024-10-14 01:40 UTC, rajeshsgr commented
I have done all the changes, the build is failing for a file which i have not changed or worked on

2024-10-14 04:11 UTC, Ritabrata1080 approved these changes

2024-10-14 04:11 UTC, Ritabrata1080 commented
> I have done all the changes, the build is failing for a file which i have not changed or worked on

Approved. Please squash the commits once.

2024-10-14 20:36 UTC, rajeshsgr commented
Squashed, please check

2024-10-15 04:23 UTC, Ritabrata1080 approved these changes

2024-10-15 04:25 UTC, Ritabrata1080 commented
This checks might be failing due to addition of main() in the code. I think only driver code is allowed to be pushed and not the main method.

2024-10-15 15:32 UTC, rajeshsgr commented
I have removed the main, it fails when it compiles - MultiArrayConcatenationSnippet.java  and says it uses unchecked or unsafe operations. This is a file which i have not changed or worked on .

2024-11-03 10:34 UTC, iluwatar requested changes
Please check the following
- The build is failing
- README.md changes are missing (see https://github.com/iluwatar/30-seconds-of-java/blob/master/CONTRIBUTE.md)

2025-01-18 04:10 UTC, closed without merging