Hacktoberfest  - convert newline caracter to formart unix or dos
iluwatar/30-seconds-of-java pull request #83
Opened 2020-10-08 15:42 UTC by vicenthy

2020-10-09 21:08 UTC, vicenthy commented
Anyone can i help me with chacklist style plugin?

2020-10-10 13:36 UTC, grzesiekkedzior commented
At first glance the Readme file has bad indentation. You are not using a local variable 'var' consistently. Some files have EOF. You try add snippet and on the other hand change another in one PR. ConvertNewLineFileToDosOrUnix.java file doesn't have License.

2020-10-12 23:53 UTC, vicenthy commented
> At first glance the Readme file has bad indentation. You are not using a local variable 'var' consistently. Some files have EOF. You try add snippet and on the other hand change another in one PR. ConvertNewLineFileToDosOrUnix.java file doesn't have License.

tranks for your help :)

2020-11-08 17:18 UTC, iluwatar requested changes

2020-11-08 17:18 UTC, iluwatar commented on README.md
> +[![Convert newline caracter unix to dos](https://img.shields.io/badge/-Convert%20newline%20caracter%20unix%20to%20dos-e1b050)](#Convert-newline-caracter-unix-to-dos) [![link](https://img.shields.io/b
Fix spelling, caracter -> character, unix -> Unix, dos -> DOS

2020-11-08 17:18 UTC, iluwatar commented on src/main/java/file/ConvertNewLineFileToDosOrUnix.java
> +   * @param fileOut Path file to convert
Should be output file

2020-11-08 17:18 UTC, iluwatar commented on src/main/java/file/ConvertNewLineFileToDosOrUnix.java
> +    charSet = charSet != null ? charSet : "ISO-8859-1";
Maybe check for empty string as well?

2020-11-08 17:18 UTC, iluwatar commented on src/main/java/file/ConvertNewLineFileToDosOrUnix.java
> +    BufferedReader reader = new BufferedReader(new FileReader(new File(fileIn)));
I suggest we use try-with-resources to automatically close the writer and reader

2020-11-08 17:18 UTC, iluwatar commented on src/main/java/file/ConvertNewLineFileToDosOrUnix.java
> +        e.printStackTrace();
Probably would be better to let the exception be thrown to the caller

2020-11-08 17:18 UTC, iluwatar commented on src/main/java/file/ConvertNewLineFileToDosOrUnix.java
> +      throws IOException {
Same comments as for the above method

2020-11-08 17:18 UTC, iluwatar commented on src/main/java/string/ReversStringSnippet.java
> +    return new StringBuilder(result).reverse().toString();
Why this has been changed?

2020-11-08 17:18 UTC, iluwatar commented on src/test/java/file/ConvertNewLineFileToDosOrUnixTest.java
> +          Files.readAllLines(Paths.get("src/test/resources/windowsFileText.txt")).stream().count();
```suggestion
          Files.readAllLines(Paths.get("src/test/resources/windowsFileText.txt")).size();

```

2020-11-08 17:18 UTC, iluwatar commented on src/test/java/file/ConvertNewLineFileToDosOrUnixTest.java
> +        e.printStackTrace();
Let the exception fly

2020-11-08 17:18 UTC, iluwatar commented on src/test/java/file/ConvertNewLineFileToDosOrUnixTest.java
> +  public void testconvertCrlfToLf() {
Same comments as for the above method

2020-11-08 17:18 UTC, iluwatar commented on src/test/java/string/ReversStringSnippetTest.java
> +    assertEquals(normalizestring, ReversStringSnippet.reverseString("abc DEF123ÅÄÖ"));
No need for this change

2020-11-08 17:19 UTC, iluwatar commented
@vicenthy please find the review comments above. Let me know when you're ready for another review by commenting in this thread.

2022-12-01 16:22 UTC, PraveenNanda124 reviewed
Good work

2023-02-14 19:53 UTC, closed without merging